trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- script: |
    terraform --version
  displayName: 'Check Terraform Version'

- script: |
    terraform init
  workingDirectory: Parent_module
  displayName: 'Terraform Init'

- script: |
    terraform validate
  workingDirectory: Parent_module
  displayName: 'Terraform Validate'

- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'Azure Resource Manager'
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_module'
    inlineScript: |
      terraform plan -input=false