trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  displayName: 'Checkout repository'

- script: |
    terraform --version
  displayName: 'Check Terraform Version'

- script: |
    terraform init
  workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_module'
  displayName: 'Terraform Init'

- script: |
    terraform validate
  workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_module'
  displayName: 'Terraform Validate'

- script: |
    terraform plan -input=false
  workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_module'
  displayName: 'Terraform Plan'